<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>DevBoxKeepAwake</AssemblyName>
    <RootNamespace>DevBoxKeepAwake</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Product>DevBox Keep Awake</Product>
    <AssemblyTitle>DevBox Keep Awake</AssemblyTitle>
    <NeutralLanguage>en</NeutralLanguage>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="app.ico" />
  </ItemGroup>

</Project>